server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: azure/application-gateway
      appgw.ingress.kubernetes.io/override-frontend-port: "80"
    hosts:
      - argocd.steadfast.kasunt.fe.gl00.net
config:
  url: http://argocd.steadfast.kasunt.fe.gl00.net