apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-microservices-project
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Azure microservices demo

  sourceRepos:
  - '*'

  destinations:
  - name: kasunt-sf-west-cluster
    namespace: apps