apiVersion: v1
kind: Secret
metadata:
  name: argocd-azure-oci-repo-credentials
  namespace: gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: azure-charts
  enableOCI: "true"
  password: "$ACR_OCI_PASSWORD"
  type: helm
  url: kasuntimagesacr.azurecr.io
  username: kasuntimagesacr
